### The script contains:

#### 1. Importing Libraries & Data
#### 2. Data Quality & Consistency Check
#### 3. Data Wrangling
#### 4. Data Export

#### 1. Importing Libraries & Data

In [1]:
# Import Libraries

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [2]:
# Import Data

path = r'/Users/queency_yustiawan/Study/CF/data analyst course/immersion/A6 exercise/Gun Violence Analysis'

df = pd.read_csv (os.path.join(path,'02. Data', 'Original Data', 'gun_violence_data.csv'), index_col = False)
df

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239672,1083142,2018-03-31,Louisiana,Rayne,North Riceland Road and Highway 90,0,0,http://www.gunviolencearchive.org/incident/108...,http://www.klfy.com/news/local/rayne-woman-cha...,False,...,0::25,0::Adult 18+,0::Female,0::Jhkeya Tezeno,NaN,"0::Unharmed, Arrested",0::Subject-Suspect,http://www.klfy.com/news/local/rayne-woman-cha...,NaN,NaN
239673,1083139,2018-03-31,Louisiana,Natchitoches,247 Keyser Ave,1,0,http://www.gunviolencearchive.org/incident/108...,http://www.ksla.com/story/37854648/man-wanted-...,False,...,1::21,0::Adult 18+||1::Adult 18+,0::Male||1::Male,0::Jamal Haskett||1::Jaquarious Tyjuan Ardison,NaN,"0::Killed||1::Unharmed, Arrested",0::Victim||1::Subject-Suspect,http://www.ksla.com/story/37854648/man-wanted-...,23.0,31.0
239674,1083151,2018-03-31,Louisiana,Gretna,1300 block of Cook Street,0,1,http://www.gunviolencearchive.org/incident/108...,http://www.nola.com/crime/index.ssf/2018/04/sh...,False,...,0::21,0::Adult 18+,0::Male,NaN,NaN,0::Injured,0::Victim,http://www.nola.com/crime/index.ssf/2018/04/sh...,85.0,7.0
239675,1082514,2018-03-31,Texas,Houston,12630 Ashford Point Dr,1,0,http://www.gunviolencearchive.org/incident/108...,https://www.chron.com/news/houston-texas/houst...,False,...,0::42,0::Adult 18+,0::Male,0::Leroy Ellis,NaN,0::Killed,0::Victim,http://www.khou.com/article/news/hpd-investiga...,149.0,17.0
239676,1081940,2018-03-31,Maine,Norridgewock,434 Skowhegan Rd,2,0,http://www.gunviolencearchive.org/incident/108...,https://www.centralmaine.com/2018/03/31/police...,False,...,0::58||1::62,0::Adult 18+||1::Adult 18+,0::Female||1::Male,0::Marie Lancaster Hale||1::William Hale,1::Significant others - current or former,0::Killed||1::Killed,0::Victim||1::Subject-Suspect,https://www.centralmaine.com/2018/03/31/police...,111.0,3.0

In [3]:
# checking data info & shape

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 29 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   incident_id                  239677 non-null  int64
 1   date                         239677 non-null  object
 2   state                        239677 non-null  object
 3   city_or_county               239677 non-null  object
 4   address                      223180 non-null  object
 5   n_killed                     239677 non-null  int64
 6   n_injured                    239677 non-null  int64
 7   incident_url                 239677 non-null  object
 8   source_url                   239209 non-null  object
 9   incident_url_fields_missing  239677 non-null  bool
 10  congressional_district       227733 non-null  float64
 11  gun_stolen                   140179 non-null  object
 12  gun_type                     140226 non-null  object
 13  incident_characteristics     239351 non-null  object
 14  latitude                     231754 non-null  float64
 15  location_description         42089 non-null   object
 16  longitude                    231754 non-null  float64
 17  n_guns_involved              140226 non-null  float64
 18  notes                        158660 non-null  object
 19  participant_age              147379 non-null  object
 20  participant_age_group        197558 non-null  object
 21  participant_gender           203315 non-null  object
 22  participant_name             117424 non-null  object
 23  participant_relationship     15774 non-null   object
 24  participant_status           212051 non-null  object
 25  participant_type             214814 non-null  object
 26  sources                      239068 non-null  object
 27  state_house_district         200905 non-null  float64
 28  state_senate_district        207342 non-null  float64
dtypes: bool(1), float64(6), int64(3), object(19)
memory usage: 51.4+ MB

In [4]:
# original data descriptive analysis

df.describe()

,incident_id,n_killed,n_injured,congressional_district,latitude,longitude,n_guns_involved,state_house_district,state_senate_district
count,2.396770e+05,239677.000000,239677.000000,227733.000000,231754.000000,231754.000000,140226.000000,200905.000000,207342.00000
mean,5.593343e+05,0.252290,0.494007,8.001265,37.546598,-89.338348,1.372442,55.447132,20.47711
std,2.931287e+05,0.521779,0.729952,8.480835,5.130763,14.359546,4.678202,42.048117,14.20456
min,9.211400e+04,0.000000,0.000000,0.000000,19.111400,-171.429000,1.000000,1.000000,1.00000
25%,3.085450e+05,0.000000,0.000000,2.000000,33.903400,-94.158725,1.000000,21.000000,9.00000
50%,5.435870e+05,0.000000,0.000000,5.000000,38.570600,-86.249600,1.000000,47.000000,19.00000
75%,8.172280e+05,0.000000,1.000000,10.000000,41.437375,-80.048625,1.000000,84.000000,30.00000
max,1.083472e+06,50.000000,53.000000,53.000000,71.336800,97.433100,400.000000,901.000000,94.00000

#### 2. Data Quality & Consistency Check

In [5]:
# Checking mixed type data columns

for col in df.columns.tolist():
    mix = (df[[col]].map(type) != df[[col]].iloc[0].apply(type)).any(axis=1)
    if len(df[mix]) > 0 :
        print (col)

address
source_url
gun_stolen
gun_type
incident_characteristics
location_description
notes
participant_age
participant_age_group
participant_gender
participant_name
participant_relationship
participant_status
participant_type
sources

In [6]:
# Changing data type for mixed type columns

df['address'] = df['address'].astype('str')
df['source_url'] = df['source_url'].astype('str')
df['gun_stolen'] = df['gun_stolen'].astype('str')
df['gun_type'] = df['gun_type'].astype('str')
df['incident_characteristics'] = df['incident_characteristics'].astype('str')
df['location_description'] = df['location_description'].astype('str')
df['notes'] = df['notes'].astype('str')
df['participant_age'] = df['participant_age'].astype('str')
df['participant_age_group'] = df['participant_age_group'].astype('str')
df['participant_gender'] = df['participant_gender'].astype('str')
df['participant_name'] = df['participant_name'].astype('str')
df['participant_relationship'] = df['participant_relationship'].astype('str')
df['participant_status'] = df['participant_status'].astype('str')
df['participant_type'] = df['participant_type'].astype('str')
df['sources'] = df['sources'].astype('str')

In [7]:
# Checking missing data values

df.isnull().sum()

incident_id                        0
date                               0
state                              0
city_or_county                     0
address                            0
n_killed                           0
n_injured                          0
incident_url                       0
source_url                         0
incident_url_fields_missing        0
congressional_district         11944
gun_stolen                         0
gun_type                           0
incident_characteristics           0
latitude                        7923
location_description               0
longitude                       7923
n_guns_involved                99451
notes                              0
participant_age                    0
participant_age_group              0
participant_gender                 0
participant_name                   0
participant_relationship           0
participant_status                 0
participant_type                   0
sources                            0
state_house_district           38772
state_senate_district          32335
dtype: int64

In [8]:
# Imputting some of the missing string value as 'Unknown'

df['address'].fillna('Unknown', inplace = True)
df['source_url'].fillna('Unknown', inplace = True)
df['gun_stolen'].fillna('Unknown', inplace = True)
df['gun_type'].fillna('Unknown', inplace = True)
df['incident_characteristics'].fillna('Unknown', inplace = True)
df['location_description'].fillna('Unknown', inplace = True)
df['participant_age'].fillna('Unknown', inplace = True)
df['participant_age_group'].fillna('Unknown', inplace = True)
df['participant_gender'].fillna('Unknown', inplace = True)
df['participant_relationship'].fillna('Unknown', inplace = True)
df['participant_status'].fillna('Unknown', inplace = True)
df['participant_type'].fillna('Unknown', inplace = True)

# The of rest of the columns will be dropped due to no relation with the analysis, so the data will not be imputted.

In [9]:
# Checking for duplicate data

df_duplicates = df[df.duplicated()]
df_duplicates

Empty DataFrame
Columns: [incident_id, date, state, city_or_county, address, n_killed, n_injured, incident_url, source_url, incident_url_fields_missing, congressional_district, gun_stolen, gun_type, incident_characteristics, latitude, location_description, longitude, n_guns_involved, notes, participant_age, participant_age_group, participant_gender, participant_name, participant_relationship, participant_status, participant_type, sources, state_house_district, state_senate_district]
Index: []

[0 rows x 29 columns]

#### 3. Data Wrangling

In [11]:
# Dropping unneeded columns for analysis

df = df.drop(columns=['incident_url', 'source_url', 'incident_url_fields_missing', 'congressional_district', 'gun_type', 'location_description',
                      'notes','participant_name', 'sources','state_house_district','state_senate_district','gun_stolen'])
df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...

In [12]:
# Convert 'date' column into datatime format

df['date'] = pd.to_datetime(df['date'])

# Exctract day of the week, day, month, and year

df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['day_of_week'] = df['date'].dt.day_name()

In [13]:
# Set max display on column

pd.set_option('display.max_columns', None)

In [14]:
df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,day,month,year,day_of_week
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,1,1,2013,Tuesday
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,5,1,2013,Saturday
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,7,1,2013,Monday

In [15]:
# Creating a function to categorise events based on the 'incident_characteristics'

def categorise_event(incident_characteristics):
    if 'Gang involvement' in incident_characteristics:
        return 'Gang involvement'
    elif 'Suicide' in incident_characteristics:
        return 'Suicide'
    elif 'Armed robbery' in incident_characteristics:
        return 'Armed robbery'
    elif 'Drug involvement' in incident_characteristics:
        return 'Drug involvement'
    elif 'Accidental shooting' in incident_characteristics:
        return 'Accidental shooting'
    elif 'Home Invasion' in incident_characteristics:
        return 'Home Invasion'
    elif 'Domestic Violence' in incident_characteristics:
        return 'Domestic Violence'
    elif 'Bar/club incident' in incident_characteristics:
        return 'Bar/club incident'
    elif 'Accidental Shooting' in incident_characteristics:
        return 'Accidental Shooting'
    elif 'Gun at school' in incident_characteristics:
        return 'Gun at school'
    elif 'Defensive Use' in incident_characteristics:
        return 'Defensive Use'
    elif 'Car-jacking' in incident_characteristics:
        return 'Car-jacking'
    else:
        return 'Others'

# Creating the 'incident_event' column based on the categorisation function

df['incident_event'] = df['incident_characteristics'].apply(categorise_event)

df.incident_event.value_counts()

incident_event
Others                 156334
Armed robbery           19586
Drug involvement        15343
Domestic Violence        8344
Home Invasion            7976
Accidental Shooting      7629
Suicide                  6101
Gang involvement         5677
Bar/club incident        4149
Car-jacking              3657
Defensive Use            2795
Gun at school            2086
Name: count, dtype: int64

In [16]:
# Creating a function to categorise shots/no shots happeneddef categorise_event(incident_characteristics):

def categorise_shots(incident_characteristics):
    if 'Non-Shooting Incident' in incident_characteristics:
        return 'Non-Shooting Incident'
    elif 'Shot - Dead' in incident_characteristics:
        return 'Shot - Dead'
    elif 'Shot - Wounded/Injured' in incident_characteristics:
        return 'Shot - Wounded/Injured'
    elif 'Shots Fired - No Injuries' in incident_characteristics:
        return 'Shots Fired - No Injuries'
    else:
        return 'Unknown'
    
# Creating the 'incident_shot' column based on the categorisation function

df['incident_shot'] = df['incident_characteristics'].apply(categorise_shots)

df.incident_shot.value_counts()

incident_shot
Shot - Wounded/Injured       85596
Shot - Dead                  53405
Non-Shooting Incident        44837
Shots Fired - No Injuries    34721
Unknown                      21118
Name: count, dtype: int64

In [17]:
df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,day,month,year,day_of_week,incident_event,incident_shot
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Others,Shot - Wounded/Injured
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Gang involvement,Shot - Dead
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,1,1,2013,Tuesday,Bar/club incident,Shot - Dead
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,5,1,2013,Saturday,Drug involvement,Shot - Dead
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,7,1,2013,Monday,Suicide,Shot - Dead

In [23]:
# extract data from participant_age_group column into new columns

def extract_age_group_column(age_group):
    df['n_adult'] = df[age_group].str.count('Adult')
    df['n_teen'] = df[age_group].str.count('Teen')
    df['n_child'] = df[age_group].str.count('Child')
    return df

df = extract_age_group_column('participant_age_group')

df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,day,month,year,day_of_week,incident_event,incident_shot,n_adult,n_teen,n_child,n_male,n_female
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Others,Shot - Wounded/Injured,5,0,0,3,1
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Gang involvement,Shot - Dead,4,0,0,1,0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,1,1,2013,Tuesday,Bar/club incident,Shot - Dead,5,0,0,5,0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,5,1,2013,Saturday,Drug involvement,Shot - Dead,4,0,0,3,1
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,7,1,2013,Monday,Suicide,Shot - Dead,3,1,0,2,2

In [24]:
# extract data from participant_gender column into new columns

def extract_gender_column(gender):
    df['n_male'] = df[gender].str.count('Male')
    df['n_female'] = df[gender].str.count('Female')
    return df

df = extract_gender_column('participant_gender')

df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,day,month,year,day_of_week,incident_event,incident_shot,n_adult,n_teen,n_child,n_male,n_female
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Others,Shot - Wounded/Injured,5,0,0,3,1
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Gang involvement,Shot - Dead,4,0,0,1,0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,1,1,2013,Tuesday,Bar/club incident,Shot - Dead,5,0,0,5,0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,5,1,2013,Saturday,Drug involvement,Shot - Dead,4,0,0,3,1
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,7,1,2013,Monday,Suicide,Shot - Dead,3,1,0,2,2

In [26]:
# extract data from participant_type column into new columns

def extract_type_column(type):
    df['n_victim'] = df[type].str.count('Victim')
    df['n_suspect'] = df[type].str.count('Suspect')
    return df

df = extract_type_column('participant_type')

df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_characteristics,latitude,longitude,n_guns_involved,participant_age,participant_age_group,participant_gender,participant_relationship,participant_status,participant_type,day,month,year,day_of_week,incident_event,incident_shot,n_adult,n_teen,n_child,n_male,n_female,n_victim,n_suspect
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,nan,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Others,Shot - Wounded/Injured,5,0,0,3,1,4,1
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330,NaN,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,nan,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,1,1,2013,Tuesday,Gang involvement,Shot - Dead,4,0,0,1,0,4,1
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377,2.0,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,nan,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,1,1,2013,Tuesday,Bar/club incident,Shot - Dead,5,0,0,5,0,3,2
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020,NaN,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,nan,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,5,1,2013,Saturday,Drug involvement,Shot - Dead,4,0,0,3,1,3,1
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569,2.0,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,7,1,2013,Monday,Suicide,Shot - Dead,3,1,0,2,2,3,1

In [28]:
# Dropping unused columns

df = df.drop(columns=['incident_characteristics', 'participant_age', 'participant_age_group', 'participant_gender',
                      'participant_relationship', 'participant_status', 'participant_type'])
             
df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,latitude,longitude,n_guns_involved,day,month,year,day_of_week,incident_event,incident_shot,n_adult,n_teen,n_child,n_male,n_female,n_victim,n_suspect
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,40.3467,-79.8559,NaN,1,1,2013,Tuesday,Others,Shot - Wounded/Injured,5,0,0,3,1,4,1
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,33.9090,-118.3330,NaN,1,1,2013,Tuesday,Gang involvement,Shot - Dead,4,0,0,1,0,4,1
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,41.4455,-82.1377,2.0,1,1,2013,Tuesday,Bar/club incident,Shot - Dead,5,0,0,5,0,3,2
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,39.6518,-104.8020,NaN,5,1,2013,Saturday,Drug involvement,Shot - Dead,4,0,0,3,1,3,1
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,36.1140,-79.9569,2.0,7,1,2013,Monday,Suicide,Shot - Dead,3,1,0,2,2,3,1

In [29]:
# Reorganising columns order

df = df[['incident_id', 'date','day_of_week', 'day', 'month','year','state', 'city_or_county', 'address','latitude',
        'longitude', 'incident_event', 'incident_shot','n_guns_involved', 'n_killed', 'n_injured','n_adult',
        'n_teen', 'n_child', 'n_male', 'n_female', 'n_victim', 'n_suspect']]

df.head()

,incident_id,date,day_of_week,day,month,year,state,city_or_county,address,latitude,longitude,incident_event,incident_shot,n_guns_involved,n_killed,n_injured,n_adult,n_teen,n_child,n_male,n_female,n_victim,n_suspect
0,461105,2013-01-01,Tuesday,1,1,2013,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,40.3467,-79.8559,Others,Shot - Wounded/Injured,NaN,0,4,5,0,0,3,1,4,1
1,460726,2013-01-01,Tuesday,1,1,2013,California,Hawthorne,13500 block of Cerise Avenue,33.9090,-118.3330,Gang involvement,Shot - Dead,NaN,1,3,4,0,0,1,0,4,1
2,478855,2013-01-01,Tuesday,1,1,2013,Ohio,Lorain,1776 East 28th Street,41.4455,-82.1377,Bar/club incident,Shot - Dead,2.0,1,3,5,0,0,5,0,3,2
3,478925,2013-01-05,Saturday,5,1,2013,Colorado,Aurora,16000 block of East Ithaca Place,39.6518,-104.8020,Drug involvement,Shot - Dead,NaN,4,0,4,0,0,3,1,3,1
4,478959,2013-01-07,Monday,7,1,2013,North Carolina,Greensboro,307 Mourning Dove Terrace,36.1140,-79.9569,Suicide,Shot - Dead,2.0,2,2,3,1,0,2,2,3,1

In [34]:
# Wrangled data descriptive analysis

df.describe()

,incident_id,date,day,month,year,latitude,longitude,n_guns_involved,n_killed,n_injured,n_adult,n_teen,n_child,n_male,n_female,n_victim,n_suspect
count,2.396770e+05,239677,239677.000000,239677.000000,239677.000000,231754.000000,231754.000000,140226.000000,239677.000000,239677.000000,239677.000000,239677.000000,239677.000000,239677.000000,239677.000000,239677.000000,239677.000000
mean,5.593343e+05,2016-03-13 00:26:19.645940480,15.773787,6.351786,2015.711629,37.546598,-89.338348,1.372442,0.252290,0.494007,1.278533,0.106873,0.019059,1.289615,0.180126,0.805501,0.831381
min,9.211400e+04,2013-01-01 00:00:00,1.000000,1.000000,2013.000000,19.111400,-171.429000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.085450e+05,2015-03-07 00:00:00,8.000000,3.000000,2015.000000,33.903400,-94.158725,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,5.435870e+05,2016-04-05 00:00:00,16.000000,6.000000,2016.000000,38.570600,-86.249600,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000
75%,8.172280e+05,2017-04-03 00:00:00,23.000000,9.000000,2017.000000,41.437375,-80.048625,1.000000,0.000000,1.000000,2.000000,0.000000,0.000000,2.000000,0.000000,1.000000,1.000000
max,1.083472e+06,2018-03-31 00:00:00,31.000000,12.000000,2018.000000,71.336800,97.433100,400.000000,50.000000,53.000000,103.000000,27.000000,11.000000,61.000000,23.000000,102.000000,63.000000
std,2.931287e+05,NaN,8.831929,3.447656,1.225870,5.130763,14.359546,4.678202,0.521779,0.729952,1.147596,0.416672,0.169709,1.067821,0.458493,0.839808,0.974121

#### 4. Data Export

In [35]:
# Export data to pickle

df.to_pickle(os.path.join(path, '02. Data','Prepared Data', 'gun_violence_data_wrangled.pkl'))

In [36]:
# Export data to csv

df.to_csv(os.path.join(path, '02. Data', 'Prepared Data', 'gun_violence_data_wrangled.csv'))